### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by vincent-zurczak** [nimmis/docker-java#1]
Hello! :smile: 

First, thank you for these images. There are very convenient.
However, I run on an issue. We have integration tests based on these images. 6 or 7 months ago, everything was working fine. I tested today, and nothing works anymore.

Changing the Ubuntu version does not only impact the Java stuff, but also everything we want to deploy in the image. The real issue is that it is not possible to get the Java image that worked with Ubuntu 14.04. They have the same tag, but not the same system. :/

That's really annoying, as it means that images that work today may not work anymore in some months. Tags should include both the Java and the OS versions.

**Comment by nimmis** [comment]
I try to include OS version in tags like oracle-8-jdk-14.04 or 14.04-oracle-8-jdk and restore the 14.04 builds.

**Comment by vincent-zurczak** [comment]
That would be great. Thanks. :+1:

**Comment by nimmis** [comment]
I have updated, all Ubuntu 14.04 have **14.04-** as prefix, check [README.md](https://github.com/nimmis/docker-java/blob/master/README.md#tags) for a full TAG list.

Please give feedback if this solved you problem so I can close this issue

**Comment by vincent-zurczak** [comment]
I'll give it a try tomorrow. Thanks. ;)

**Comment by vincent-zurczak** [comment]
It works. Thanks. :+1:
